name: dbt CD

on:
  push:
    branches:
      - main

jobs:
  dbt-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dbt
        run: pip install dbt-core dbt-duckdb

      - name: Setup dbt profile
        run: |
          mkdir -p ~/.dbt
          # Create .dbt folder in GitHub machine (it doesn't exist by default)

          echo "dbt_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: dbt.duckdb" > ~/.dbt/profiles.yml
          # Create profiles.yml file (this tells dbt which database to use)

      - name: Run dbt
        run: |
          dbt deps    # install dependencies (if any)
          dbt seed    # load CSV files into database
          dbt build   # run models + tests (full pipeline)